version: '3'

volumes:
  users-postgres-data:
    driver: local
  auth-postgres-data:
    driver: local
  history-postgres-data:
    driver: local

services:
  #
  # USERS SERVICE
  #
  users-postgres:
    container_name: users-postgres
    image: postgres
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
  users-api:
    container_name: users-api
    image: cagodoy/tenpo-users-api:0.0.5
    ports:
      - 5020:5020
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@users-postgres:5432/postgres?sslmode=disable
      - PORT=5020
    depends_on:
      - users-postgres
    links:
      - users-postgres

  #
  # AUTH SERVICE
  #
  auth-postgres:
    container_name: auth-postgres
    image: postgres
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
  auth-api:
    container_name: auth-api
    image: cagodoy/tenpo-auth-api:0.0.10
    ports:
      - 5010:5010
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@auth-postgres:5432/postgres?sslmode=disable
      - PORT=5010
      - USERS_HOST=users-api
      - USERS_PORT=5020
      - JWT_SECRET=jwt_very_secret
    depends_on:
      - auth-postgres
    links:
      - auth-postgres

  #
  # RESTAURANTS SERVICE
  #
  restaurants-api:
    container_name: restaurants-api
    image: cagodoy/tenpo-restaurants-api:0.0.6
    ports:
      - 5030:5030
    environment:
      - PORT=5030
      - NATS_HOST=nats
      - NATS_PORT=4222
      - API_KEY=AIzaSyAH_cK89vxSSQy3rLjwByCnCUa7ZWR4uqE
    depends_on:
      - nats
    links:
      - nats

  #
  # HISTORY SERVICE
  #
  history-postgres:
    container_name: history-postgres
    image: postgres
    volumes:
      - history-postgres-data:/var/lib/postgresql/data
  history-api:
    container_name: history-api
    image: cagodoy/tenpo-history-api:0.0.4
    ports:
      - 5040:5040
    environment:
      - PORT=5040
      - POSTGRES_DSN=postgres://postgres:postgres@history-postgres:5432/postgres?sslmode=disable
      - NATS_HOST=nats
      - NATS_PORT=4222
    depends_on:
      - nats
      - history-postgres
    links:
      - nats
      - history-postgres

  #
  # GATEWAY SERVICE
  #
  gateway-api:
    container_name: gateway-api
    image: cagodoy/tenpo-gateway-api:0.0.3
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - AUTH_HOST=auth-api
      - AUTH_PORT=5010
      - RESTAURANTS_HOST=restaurants-api
      - RESTAURANTS_PORT=5030
      - HISTORY_HOST=history-api
      - HISTORY_PORT=5040

  #
  # NATS SERVICE
  #
  nats:
    container_name: nats
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
