apiVersion: v1
kind: ConfigMap
metadata:
  name: history-postgres-config
  labels:
    app: history-postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: history-postgres-pv-volume
  labels:
    type: local
    app: history-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/mnt/data/history'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: history-postgres-pv-claim
  labels:
    app: history-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: history-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: history-postgres
    spec:
      nodeSelector:
        service: databases
      containers:
        - name: history-postgres
          image: postgres:10.4
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: history-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: history-postgresdb
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: history-postgresdb
          persistentVolumeClaim:
            claimName: history-postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: history-postgres
  labels:
    app: history-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: history-postgres
