apiVersion: v1
kind: Service
metadata:
  name: history-api
  labels:
    app: history-api
    service: history-api
spec:
  ports:
    - port: 5040
      name: grpc
  selector:
    app: history-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenpo-history-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-api
  labels:
    app: history-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-api
  template:
    metadata:
      labels:
        app: history-api
    spec:
      nodeSelector:
        service: general
      serviceAccountName: tenpo-history-api
      containers:
        - name: history-api
          image: cagodoy/tenpo-history-api:0.0.4
          ports:
            - containerPort: 5040
          env:
            - name: POSTGRES_DSN
              value: postgres://postgres:postgres@history-postgres:5432/postgres?sslmode=disable
            - name: PORT
              value: '5040'
            - name: NATS_HOST
              value: nats
            - name: NATS_PORT
              value: '4222'
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: history-postgresdb
          persistentVolumeClaim:
            claimName: history-postgres-pv-claim
